name: CI/CD Pipeline

on:
  push:
    branches: [ main ]  # Triggers when you push to the main branch

jobs:
  build-test-push:
    runs-on: ubuntu-latest  # Uses a virtual Linux machine

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Clones your repo into the GitHub Actions runner

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ kavya5229 }}/myapp:latest .

    - name: Push Docker image
      run: docker push ${{ kavya5229 }}/myapp:latest
